/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import styled from "styled-components";
import logo from "../images/icon3.svg";

export default function MyComponent() {
  return (
    <Div>
      <Img loading="lazy" srcSet="..." />
      <Div2>
        <Div3>
          <Div4>About</Div4>
          <Div5>Blog</Div5>
          <Div6>
            <Img2 loading="lazy" srcSet={logo}/>
            {/* <Img3 loading="lazy" srcSet="..." /> */}
            <Div4>MEMORYHAVEN</Div4>
          </Div6>
        </Div3>
        <Div7>Be Remembered.</Div7>
        <Img4 loading="lazy" srcSet="..." />
      </Div2>
    </Div>
  );
}

const Div = styled.div`
  disply: flex;
  flex-direction: column;
  overflow: hidden;
  position: relative;
  display: flex;
  min-height: 982px;
  padding-right: 20px;
  padding-left: 20px;
`;

const Img = styled.img`
  position: absolute;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
`;

const Div2 = styled.div`
  position: relative;
  align-self: start;
  display: flex;
  margin-top: 28px;
  margin-left: 152px;
  margin-bottom: 26px;
  width: 619px;
  max-width: 100%;
  flex-direction: column;
`;

const Div3 = styled.div`
  align-self: stretch;
  display: flex;
  width: 100%;
  align-items: flex-start;
  justify-content: space-between;
  gap: 20px;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
    justify-content: center;
  }
`;

const Div4 = styled.div`
  color: #fff;
  font-family: Swis721 BT, sans-serif;
  font-size: 12px;
  font-weight: 400;
  align-self: center;
  margin-top: auto;
  margin-bottom: auto;
`;

const Div5 = styled.div`
  color: #fff;
  font-family: Swis721 BT, sans-serif;
  font-size: 12px;
  font-weight: 400;
  align-self: center;
  margin-top: auto;
  margin-bottom: auto;
`;

const Div6 = styled.div`
  align-items: flex-start;
  align-self: stretch;
  display: flex;
  justify-content: space-between;
  gap: 6px;
`;

const Img2 = styled.img`
  aspect-ratio: 1;
  object-fit: cover;
  object-position: center;
  width: 15px;
  overflow: hidden;
`;

const Img3 = styled.img`
  aspect-ratio: 8.33;
  object-fit: cover;
  object-position: center;
  width: 75px;
  overflow: hidden;
  align-self: center;
  margin-top: auto;
  margin-bottom: auto;
`;

const Div7 = styled.div`
  color: #fff;
  font-family: Swis721 BT, sans-serif;
  font-size: 64px;
  font-weight: 400;
  max-width: 541px;
  align-self: start;
  margin-top: 161px;
  @media (max-width: 991px) {
    max-width: 100%;
    font-size: 40px;
  }
`;

const Img4 = styled.img`
  aspect-ratio: 1;
  object-fit: cover;
  object-position: center;
  width: 36px;
  border-radius: 10px;
  overflow: hidden;
  align-self: end;
  margin-top: 669px;
  margin-right: 23px;
  @media (max-width: 991px) {
    margin-top: 200px;
    margin-right: 10px;
  }
`;
